import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  container: {
    // flex: 1,
    marginTop: 20,
    marginHorizontal: 15,
  },
  image: {
    width: 80,
    height: 80,
  },
  viewH: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 8,
    // borderWidth: 1,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderColor: '#DCDCDC',
    backgroundColor: '#fafafafa',
    elevation: 2,
    shadowOpacity: 0.22,
    shadowRadius: 3.22,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    marginBottom: 20,
  },
  headText: {
    fontSize: 24,
    fontWeight:'bold',
    paddingStart: 24,
    color: 'black',
  },
  progress: {
    height: 10,
    borderRadius: 8,
    marginTop: 10,
    width: '100%',
  },
  card: {
    marginVertical: 20,
    borderRadius: 8,
    // borderWidth: 1,
    paddingVertical: 20,
    paddingHorizontal: 10,
    borderColor: '#DCDCDC',
    backgroundColor: '#fff',
    elevation: 2,
    shadowOpacity: 0.22,
    shadowRadius: 3.22,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
  },
  secContainer: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  circleBtn: {
    width: 100,
    height: 100,
    backgroundColor: '#0178D6',
    borderRadius: 50,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 10,
  },
  btn: {
    backgroundColor: '#DCDCDC',
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 10,
    textAlign: 'center',
    marginVertical: 10,
    marginHorizontal: 40,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  scroll: {
    paddingBottom: 40,
  },
});
export default styles;
